apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\programdata\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\programdata\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f .\docker-compose.prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-api
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: rcd
        - name: DB_PASS
          value: dontchangemeimsecure
        - name: DB_USER
          value: postgres
        - name: NODE_ENV
          value: production
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: docker.pkg.github.com/maxelweb/kubernetes-rcd/backend-rcd:latest
        imagePullPolicy: ""
        name: backend-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      imagePullSecrets:
        - name: regcred
status: {}
