apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: backend-api
    spec:
      imagePullSecrets:
      - name: rcd-secret
      containers:
      - env:
        - name: DB_PORT
          value: "2345"
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: rcd
        - name: DB_PASS
          value: dontchangemeimsecure
        - name: DB_USER
          value: postgres
        - name: NODE_ENV
          value: production
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: docker.pkg.github.com/maxelweb/kubernetes-rcd/backend-rcd:latest
        imagePullPolicy: IfNotPresent
        name: backend-api
        ports:
        - containerPort: 3000
        resources: {} # Hardware resources allocation
      restartPolicy: Always
      serviceAccountName: ""
      volumes: []
status: {}
