apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-api
    spec:
      containers:
      - args:
        - sh
        - -c
        - npm install && npm start
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: rcd
        - name: DB_PASS
          value: dontchangemeimsecure
        - name: DB_USER
          value: postgres
        - name: NODE_ENV
          value: production
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: node:14-alpine
        imagePullPolicy: ""
        name: backend-api
        ports:
        - containerPort: 3000
        resources: {}
        workingDir: /usr/src/Backend
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
