apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f .\docker-compose.prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: backend-api
    spec:
      imagePullSecrets:
      - name: rcd-secret
      containers:
      - env:
        - name: TYPE
          value: backend
        volumeMounts:
          - name: environment-variables-b
            mountPath: "/usr/src/Backend/.env"
            subPath: ".env"
            readOnly: false
        image: docker.pkg.github.com/maxelweb/kubernetes-rcd/backend-rcd:latest
        imagePullPolicy: Always
        name: backend-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: 
      - name: environment-variables-b
        configMap:
          name: environment-variables-b
          items:
            - key: .env
              path: .env
status: {}
