apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 3000
  selector:
    io.kompose.service: backend-api
status:
  loadBalancer: {}
