# Kubernetes - Runtimes for Concurrency and Distribution 
# 2020-2021

version: '3.1'

services:
  backend-api: 
    container_name: backend-api
    image: docker.pkg.github.com/maxelweb/kubernetes-rcd/backend-rcd:latest
    # build: ./Backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=dontchangemeimsecure
      - DB_NAME=rcd
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:3000
    depends_on:
      - redis
      - postgres

  frontend-webapp: 
    container_name: frontend-webapp
    image: docker.pkg.github.com/maxelweb/kubernetes-rcd/frontend-rcd:latest
    environment:
      - REACT_APP_API_URL=https://api.rcd.debug.ovh/
    # build: ./frontend
    ports:
      - 80:3000
    depends_on:
      - backend-api

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    depends_on: 
      - postgres

  postgres:
    container_name: postgres
    image: docker.pkg.github.com/maxelweb/kubernetes-rcd/database-rcd:latest
    build: ./Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangemeimsecure
      POSTGRES_DB: rcd
    ports: 
      - "2345:5432"
    restart: always