version: '3.1'

# Ports: 
# ------
# backend-api: 8000
# webapp: 80

services:

  backend-api: 
    image: "node:14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASS=dontchangemeimsecure
      - DB_NAME=rcd
    volumes:
      - ./Backend:/home/node/app
    expose:
      - "8000"
    command: >
      sh -c "chown -R node:node ./ && npm install && npm start"

  database:
    image: postgres:13-alpine
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangemeimsecure
      POSTGRES_DB: rcd 

  # Debug 
  db-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080