# Kubernetes - Runtimes for Concurrency and Distribution 
# 2020-2021

version: '3.1'

# Ports: 
# ------
# backend-api: 3000
# webapp: 80
# redis: 6379


networks:
  kube-rcd-net:
    driver: bridge

services:
  backend-api: 
    container_name: backend-api
    image: node:14-alpine
    # user: node
    working_dir: /usr/src/Backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=dontchangemeimsecure
      - DB_NAME=rcd
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    volumes:
      - ./Backend:/usr/src/Backend
    command: >
      sh -c "npm install && npm start"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    #networks:
      #- kube-rcd-net
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangemeimsecure
      POSTGRES_DB: rcd
    build: ./Database
    ports: 
      - "2345:5432"

  # Debug 
  db-adminer:
    container_name: db-debug-adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always