# Kubernetes - Runtimes for Concurrency and Distribution 
# 2020-2021

version: '3.1'

services:
  backend-api: 
    container_name: backend-api
    image: node:14-alpine
    # build: ./Backend
    working_dir: /usr/src/Backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=dontchangemeimsecure
      - DB_NAME=rcd
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:3000
    volumes:
      - ./Backend:/usr/src/Backend
    depends_on:
      - redis
      - postgres

  frontend-webapp: 
    container_name: frontend-webapp
    image: node:14-alpine
    # build: ./frontend
    working_dir: /usr/src/Frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/usr/src/Frontend
    depends_on:
      - backend-api

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    depends_on: 
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    build: ./Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangemeimsecure
      POSTGRES_DB: rcd
    ports: 
      - "2345:5432"
    restart: always