# Kubernetes - Runtimes for Concurrency and Distribution 
# 2020-2021

version: '3.1'

# Ports: 
# ------
# backend-api: 8000
# webapp: 80
# redis: 6379


networks:
  kube-rcd-net:
    driver: bridge

services:
  backend-api: 
    container_name: backend-api
    image: node:14-alpine
    user: node
    working_dir: /home/node
    environment:
      - NODE_ENV=production
      - DB_HOST=db-postgres
      - DB_USER=postgres
      - DB_PASS=dontchangemeimsecure
      - DB_NAME=rcd
      - REDIS_HOST=db-redis
      - REDIS_PORT=6379
    ports:
      - 8080:3000
    networks:
      - kube-rcd-net
    volumes:
      - ./Backend:/home/node
    command: >
      sh -c "npm install && npm start"

  db-redis:
    container_name: db-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - kube-rcd-net
    restart: always


  db-postgres:
    container_name: db-postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dontchangemeimsecure
      POSTGRES_DB: rcd 
    restart: always 

  # Debug 
  db-adminer:
    container_name: db-debug-adminer
    image: adminer
    ports:
      - 8081:8080
    restart: always