apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-webapp
  name: frontend-webapp
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
    nodePort: 30080
  selector:
    io.kompose.service: frontend-webapp
status:
  loadBalancer: {}
