apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: c:\programdata\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.prod.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-webapp
  name: frontend-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-webapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: c:\programdata\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -f .\docker-compose.prod.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-webapp
    spec:
      containers:
      - image: docker.pkg.github.com/maxelweb/kubernetes-rcd/frontend-rcd:latest
        imagePullPolicy: ""
        name: frontend-webapp
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      imagePullSecrets:
        - name: regcred
status: {}
