apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-webapp
  name: frontend-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-webapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-webapp
    spec:
      containers:
      - args:
        - sh
        - -c
        - npm install && npm run dev
        image: node:14-alpine
        imagePullPolicy: ""
        name: frontend-webapp
        ports:
        - containerPort: 3000
        resources: {}
        workingDir: /usr/src/Frontend
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
