apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-webapp
  name: frontend-webapp
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: frontend-webapp
status:
  loadBalancer: {}
