apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: backend-api
  name: backend-api
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 3000
    nodePort: 30081
  selector:
    io.kompose.service: backend-api
status:
  loadBalancer: {}
