apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: postgres
    spec:
      imagePullSecrets:
      - name: rcd-secret
      containers:
      - env:
        - name: POSTGRES_DB
          value: rcd
        - name: POSTGRES_PASSWORD
          value: dontchangemeimsecure
        - name: POSTGRES_USER
          value: postgres
        image: docker.pkg.github.com/maxelweb/kubernetes-rcd/database-rcd:latest
        imagePullPolicy: IfNotPresent
        name: postgres
        args: ["-c", "max_connections=500", "-c", "shared_buffers=256MB"]
        ports:
        - containerPort: 5432
        resources: {} # Hardware resources allocation
        # volumeMounts:
        # - name: postgres-persistent-storage
        #   mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      serviceAccountName: ""   
      # volumes:
      # - name: postgres-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: postgres-pvc
status: {}
